# Generated by Django 5.0.3 on 2024-03-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuste',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion'),
            preserve_default=False,
        ),
    ]
